version: 2
updates:
  - package-ecosystem: npm
    directory: /nodejs/express
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /
    schedule:
        interval: weekly
