version: 2
updates:
  - package-ecosystem: npm
    directory: /nodejs/express
    schedule:
      interval: cron
      cronjob: "* * 28 * *"
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: cron
      cronjob: "* * 28 * *"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "* * 28 * *"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: cron
      cronjob: "* * 28 * *"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: cron
      cronjob: "* * 28 * *"
