language: java
jvm: openjdk10
install:
  - jdk_switcher use openjdk10
jobs:
  include:
    - stage: java/spring-boot
      script:
      - cd java/spring-boot
      - ./gradlew clean build
cache:
  directories:
    - $HOME/.gradle