language: java
jvm: openjdk11
install:
  - jdk_switcher use openjdk11
jobs:
  include:
    - stage: java/spring-boot
      script:
      - cd java/spring-boot
      - ./gradlew clean build
cache:
  directories:
    - "$HOME/.gradle"