language: java
jvm: openjdk11
install:
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
jobs:
  include:
    - stage: java/spring-boot
      script:
      - cd java/spring-boot
      - ./gradlew clean build
cache:
  directories:
    - $HOME/.gradle