language: java
jdk:
  - openjdk10
jobs:
  include:
    - stage: java/spring-boot
      script:
        - java --version
        - cd java/spring-boot
        - ./gradlew clean build
cache:
  directories:
    - $HOME/.gradle