source "https://rubygems.org" do
  gem 'sinatra'
  gem 'rackup'
  gem 'puma'
  gem 'rack', '>= 3.1.12' # https://github.com/artamonovkirill/extreme-startup/security/dependabot/18
  gem 'rack-session', '>= 2.1.1' # https://github.com/artamonovkirill/extreme-startup/security/dependabot/19
  group :test do
    gem 'minitest'
    gem 'rack-test'
  end
end
