name: Gradle

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: gradle
      - run: ./gradlew build --no-daemon --max-workers 2 --scan
