name: Gradle

on:
  push:
    paths-ignore:
      - '.github/workflows/go.yml'
      - 'go/**'
      - '.github/workflows/npm.yml'
      - 'nodejs/**'
      - '.github/workflows/python.yml'
      - 'python/**'
      - '.github/workflows/ruby.yml'
      - 'ruby/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: ./gradlew build --no-daemon --max-workers 2 --scan
