name: Python

on:
  push:
    paths-ignore:
      - '.github/workflows/ruby.yml'
      - 'ruby/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement python/flask/requirements.txt
      - name: Test
        run: pytest