name: Ruby

on:
  push:
    paths:
      - '.github/workflows/ruby.yaml'
      - 'ruby/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --gemfile ruby/sinatra/Gemfile
      - name: Test
        run: rake --rakefile ruby/Rakefile
